### ISSUE TITLE
Permission denied appears randomly after closing the Replit window

### ISSUE THREAD

**Issue by OnlyAlec** [KhushrajRathod/repl.deploy#17]
## Context

All the steps in the guide work great, the bot stays awake and receives the github deploys.
However, yesterday stopped performing the deploys and also didn't start the bot.

When I checked what happened, it turned out that the `./repl.deploy`  file was missing permissions.
I applied them again and it worked wonderfully, a few hours later the permits were missing again.

- Console
```
node v12.16.1
>> ./repl.deploy --standalone node index.js
sh: 1: ./repl.deploy: Permission denied
exit status 126
```

**Comment by khrj** [comment]
Hey, this seems like a replit problem more than a repl.deploy problem.

I assume this happens because of replit's snapshot system. It's likely that replit didn't take a snapshot after you changed the file permissions, so it reverted `chmod +x` and couldn't run it...

Here's what you can try: Change the permissions again, and then open the binary in the GUI editor (you'll see garbage text, just ignore it and close it after a couple of seconds). This _should_ get replit to take a snapshot of the file with changed permissions.

Let me know if that works!

**Comment by khrj** [comment]
An alternative solution guarenteed to work is just to change your .replit file to

```
run="chmod +x ./repl.deploy && ./repl.deploy --standalone node index.js"
```

**Comment by OnlyAlec** [comment]
Right, sorry if I answer late. So, I tried the first method and it seems that works fine!. Anyways if in some hours fail, I will try the second one.  I will notify you! 

Thanks for the answer!

UPDATE:
Unfortunately I continued with the problem of permissions in the file but I think it is because of the snapshot that is created.

Apparently the snapshot is only done once (when you do the replit for the first time), since when you modify the .replit file it returns to the snapshot configuration.

Therefore, the solution was to recreate the reply but applying the new command (2nd method) so the permission is always applied every time it is started.
